// This file is autogenerated by VESC Tool

#ifndef VBMS16_CONFPARSER_H_
#define VBMS16_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		3729544411
#define SERIALIZED_CONFIG_LENGTH	338

// Functions
int32_t vbms16_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool vbms16_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void vbms16_confparser_set_defaults_main_config_t(main_config_t *conf);

// VBMS16_CONFPARSER_H_
#endif
