// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "jfbms_slave_confparser.h"

int32_t jfbms_slave_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer_append_int16(buffer, conf->slave_id, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer[ind++] = (uint8_t)conf->cells_ic1;
	buffer[ind++] = (uint8_t)conf->cells_ic2;
	buffer[ind++] = conf->temp_res;
	buffer_append_uint16(buffer, conf->temp_beta, &ind);

	return ind;
}

bool jfbms_slave_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->slave_id = buffer_get_int16(buffer, &ind);
	conf->can_baud_rate = buffer[ind++];
	conf->cells_ic1 = buffer[ind++];
	conf->cells_ic2 = buffer[ind++];
	conf->temp_res = buffer[ind++];
	conf->temp_beta = buffer_get_uint16(buffer, &ind);

	return true;
}

void jfbms_slave_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->slave_id = CONF_SLAVE_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->cells_ic1 = CONF_CELLS_IC1;
	conf->cells_ic2 = CONF_CELLS_IC2;
	conf->temp_res = CONF_TEMP_RES;
	conf->temp_beta = CONF_TEMP_BETA;
}
