// This file is autogenerated by VESC Tool

#ifndef JFBMS_SLAVE_CONF_DEFAULT_H_
#define JFBMS_SLAVE_CONF_DEFAULT_H_

// Slave ID
#ifndef CONF_SLAVE_ID
#define CONF_SLAVE_ID 2
#endif

// CAN Baud Rate
#ifndef CONF_CAN_BAUD_RATE
#define CONF_CAN_BAUD_RATE 2
#endif

// Cells IC1
#ifndef CONF_CELLS_IC1
#define CONF_CELLS_IC1 16
#endif

// Cells IC2
#ifndef CONF_CELLS_IC2
#define CONF_CELLS_IC2 0
#endif

// NTC Resistance
#ifndef CONF_TEMP_RES
#define CONF_TEMP_RES 2
#endif

// NTC Beta
#ifndef CONF_TEMP_BETA
#define CONF_TEMP_BETA 3435
#endif

// JFBMS_SLAVE_CONF_DEFAULT_H_
#endif
