// This file is autogenerated by VESC Tool

#ifndef JF_LINK_CONFXML_H_
#define JF_LINK_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		4027

// Variables
extern uint8_t data_main_config_t_[];

// JF_LINK_CONFXML_H_
#endif
