#!/usr/bin/env python3
"""
Generate qmlui_hw.c and qmlui_hw.h from a .qml file.

The QML file is compressed using Qt-compatible qCompress format
(4-byte big-endian uncompressed length prefix + zlib-compressed data)
and embedded as a const uint8_t array.

Usage:
    python create_qmlui_hw.py <input.qml> [output_dir]

If output_dir is not specified, files are written next to the input file.
"""

import sys
import os
import struct
import zlib
import textwrap


def qt_compress(data: bytes) -> bytes:
    """
    Compress data using Qt's qCompress format:
    4 bytes big-endian uncompressed size + zlib compressed data.
    """
    compressed = zlib.compress(data, 9)
    return struct.pack(">I", len(data)) + compressed


def generate_c_array(data: bytes, var_name: str, base_name: str) -> str:
    """Generate a C source file with the data as a const uint8_t array."""
    lines = []
    lines.append(f"// Auto-generated by create_qmlui_hw.py - do not edit")
    lines.append(f"")
    lines.append(f'#include "{base_name}.h"')
    lines.append(f"")
    lines.append(f"const uint8_t {var_name}[] = {{")

    # Format 16 bytes per line
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"\t{hex_vals},")

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"const uint32_t {var_name}_len = sizeof({var_name});")
    lines.append(f"")

    return "\n".join(lines)


def generate_header(var_name: str) -> str:
    """Generate a C header file declaring the array."""
    guard = "QMLUI_HW_H_"
    lines = [
        f"// Auto-generated by create_qmlui_hw.py - do not edit",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"",
        f"extern const uint8_t {var_name}[];",
        f"extern const uint32_t {var_name}_len;",
        f"",
        f"#endif /* {guard} */",
        f"",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.qml> [output_dir]")
        sys.exit(1)

    input_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(input_path) or "."

    if not os.path.isfile(input_path):
        print(f"Error: {input_path} not found")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    with open(input_path, "rb") as f:
        raw_data = f.read()

    compressed = qt_compress(raw_data)

    base_name = os.path.splitext(os.path.basename(input_path))[0]
    var_name = "data_qml_hw"

    c_content = generate_c_array(compressed, var_name, base_name)
    h_content = generate_header(var_name)

    c_path = os.path.join(output_dir, f"{base_name}.c")
    h_path = os.path.join(output_dir, f"{base_name}.h")

    with open(c_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(c_content)

    with open(h_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(h_content)

    print(f"Input:      {input_path} ({len(raw_data)} bytes)")
    print(f"Compressed: {len(compressed)} bytes ({100 * len(compressed) / len(raw_data):.1f}%)")
    print(f"Output:     {c_path}")
    print(f"            {h_path}")


if __name__ == "__main__":
    main()
