// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "vbms32_confparser.h"

int32_t vbms32_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer_append_int16(buffer, conf->controller_id, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer_append_int16(buffer, conf->can_status_rate_hz, &ind);
	buffer[ind++] = conf->wifi_mode;
	strcpy((char*)buffer + ind, conf->wifi_sta_ssid);
	ind += strlen(conf->wifi_sta_ssid) + 1;
	strcpy((char*)buffer + ind, conf->wifi_sta_key);
	ind += strlen(conf->wifi_sta_key) + 1;
	strcpy((char*)buffer + ind, conf->wifi_ap_ssid);
	ind += strlen(conf->wifi_ap_ssid) + 1;
	strcpy((char*)buffer + ind, conf->wifi_ap_key);
	ind += strlen(conf->wifi_ap_key) + 1;
	buffer[ind++] = conf->use_tcp_local;
	buffer[ind++] = conf->use_tcp_hub;
	strcpy((char*)buffer + ind, conf->tcp_hub_url);
	ind += strlen(conf->tcp_hub_url) + 1;
	buffer_append_uint16(buffer, conf->tcp_hub_port, &ind);
	strcpy((char*)buffer + ind, conf->tcp_hub_id);
	ind += strlen(conf->tcp_hub_id) + 1;
	strcpy((char*)buffer + ind, conf->tcp_hub_pass);
	ind += strlen(conf->tcp_hub_pass) + 1;
	buffer[ind++] = conf->ble_mode;
	strcpy((char*)buffer + ind, conf->ble_name);
	ind += strlen(conf->ble_name) + 1;
	buffer_append_uint32(buffer, conf->ble_pin, &ind);
	buffer_append_uint32(buffer, conf->ble_service_capacity, &ind);
	buffer_append_uint32(buffer, conf->ble_chr_descr_capacity, &ind);
	buffer_append_int16(buffer, conf->max_bal_ch, &ind);
	buffer[ind++] = (uint8_t)conf->cells_ic1;
	buffer[ind++] = (uint8_t)conf->cells_ic2;
	buffer[ind++] = conf->dist_bal;
	buffer[ind++] = conf->balance_mode;
	buffer_append_float32_auto(buffer, conf->vc_balance_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_min, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_min, &ind);
	buffer_append_float32_auto(buffer, conf->balance_max_current, &ind);
	buffer_append_float32_auto(buffer, conf->min_current_ah_wh_cnt, &ind);
	buffer_append_float32_auto(buffer, conf->min_current_sleep, &ind);
	buffer_append_float16(buffer, conf->t_charge_max, 10, &ind);
	buffer[ind++] = conf->i_measure_mode;
	buffer_append_float32_auto(buffer, conf->min_charge_current, &ind);
	buffer_append_float32_auto(buffer, conf->max_charge_current, &ind);
	buffer_append_int32(buffer, conf->sleep_timeout_reset_ms, &ind);
	buffer_append_float32_auto(buffer, conf->soc_filter_const, &ind);
	buffer_append_float16(buffer, conf->t_bal_lim_start, 10, &ind);
	buffer_append_float16(buffer, conf->t_bal_lim_end, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_min, 10, &ind);
	buffer[ind++] = conf->t_charge_mon_en;

	return ind;
}

bool vbms32_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer_get_int16(buffer, &ind);
	conf->can_baud_rate = buffer[ind++];
	conf->can_status_rate_hz = buffer_get_int16(buffer, &ind);
	conf->wifi_mode = buffer[ind++];
	strcpy(conf->wifi_sta_ssid, (char*)buffer + ind);
	ind += strlen(conf->wifi_sta_ssid) + 1;
	strcpy(conf->wifi_sta_key, (char*)buffer + ind);
	ind += strlen(conf->wifi_sta_key) + 1;
	strcpy(conf->wifi_ap_ssid, (char*)buffer + ind);
	ind += strlen(conf->wifi_ap_ssid) + 1;
	strcpy(conf->wifi_ap_key, (char*)buffer + ind);
	ind += strlen(conf->wifi_ap_key) + 1;
	conf->use_tcp_local = buffer[ind++];
	conf->use_tcp_hub = buffer[ind++];
	strcpy(conf->tcp_hub_url, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_url) + 1;
	conf->tcp_hub_port = buffer_get_uint16(buffer, &ind);
	strcpy(conf->tcp_hub_id, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_id) + 1;
	strcpy(conf->tcp_hub_pass, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_pass) + 1;
	conf->ble_mode = buffer[ind++];
	strcpy(conf->ble_name, (char*)buffer + ind);
	ind += strlen(conf->ble_name) + 1;
	conf->ble_pin = buffer_get_uint32(buffer, &ind);
	conf->ble_service_capacity = buffer_get_uint32(buffer, &ind);
	conf->ble_chr_descr_capacity = buffer_get_uint32(buffer, &ind);
	conf->max_bal_ch = buffer_get_int16(buffer, &ind);
	conf->cells_ic1 = buffer[ind++];
	conf->cells_ic2 = buffer[ind++];
	conf->dist_bal = buffer[ind++];
	conf->balance_mode = buffer[ind++];
	conf->vc_balance_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_min = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_min = buffer_get_float32_auto(buffer, &ind);
	conf->balance_max_current = buffer_get_float32_auto(buffer, &ind);
	conf->min_current_ah_wh_cnt = buffer_get_float32_auto(buffer, &ind);
	conf->min_current_sleep = buffer_get_float32_auto(buffer, &ind);
	conf->t_charge_max = buffer_get_float16(buffer, 10, &ind);
	conf->i_measure_mode = buffer[ind++];
	conf->min_charge_current = buffer_get_float32_auto(buffer, &ind);
	conf->max_charge_current = buffer_get_float32_auto(buffer, &ind);
	conf->sleep_timeout_reset_ms = buffer_get_int32(buffer, &ind);
	conf->soc_filter_const = buffer_get_float32_auto(buffer, &ind);
	conf->t_bal_lim_start = buffer_get_float16(buffer, 10, &ind);
	conf->t_bal_lim_end = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_min = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_mon_en = buffer[ind++];

	return true;
}

void vbms32_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->can_status_rate_hz = CONF_CAN_STATUS_RATE_HZ;
	conf->wifi_mode = CONF_WIFI_MODE;
	strcpy(conf->wifi_sta_ssid, CONF_WIFI_STA_SSID);
	strcpy(conf->wifi_sta_key, CONF_WIFI_STA_KEY);
	strcpy(conf->wifi_ap_ssid, CONF_WIFI_AP_SSID);
	strcpy(conf->wifi_ap_key, CONF_WIFI_AP_KEY);
	conf->use_tcp_local = CONF_USE_TCP_LOCAL;
	conf->use_tcp_hub = CONF_USE_TCP_HUB;
	strcpy(conf->tcp_hub_url, CONF_TCP_HUB_URL);
	conf->tcp_hub_port = CONF_TCP_HUB_PORT;
	strcpy(conf->tcp_hub_id, CONF_TCP_HUB_ID);
	strcpy(conf->tcp_hub_pass, CONF_TCP_HUB_PASS);
	conf->ble_mode = CONF_BLE_MODE;
	strcpy(conf->ble_name, CONF_BLE_NAME);
	conf->ble_pin = CONF_BLE_PIN;
	conf->ble_service_capacity = CONF_BLE_SERVICE_CAPACITY;
	conf->ble_chr_descr_capacity = CONF_BLE_CHR_DESCR_CAPACITY;
	conf->max_bal_ch = CONF_MAX_BAL_CH;
	conf->cells_ic1 = CONF_CELLS_IC1;
	conf->cells_ic2 = CONF_CELLS_IC2;
	conf->dist_bal = CONF_DIST_BAL;
	conf->balance_mode = CONF_BALANCE_MODE;
	conf->vc_balance_start = CONF_BALANCE_START;
	conf->vc_balance_end = CONF_BALANCE_END;
	conf->vc_charge_start = CONF_CHARGE_START;
	conf->vc_charge_end = CONF_CHARGE_END;
	conf->vc_charge_min = CONF_CHARGE_MIN;
	conf->vc_balance_min = CONF_BALANCE_MIN;
	conf->balance_max_current = CONF_BALANCE_MAX_CURRENT;
	conf->min_current_ah_wh_cnt = CONF_MIN_CURRENT_AH_WH_CNT;
	conf->min_current_sleep = CONF_MIN_CURRENT_SLEEP;
	conf->t_charge_max = CONF_T_CHARGE_MAX;
	conf->i_measure_mode = CONF_I_MEASURE_MODE;
	conf->min_charge_current = CONF_MIN_CHARGE_CURRENT;
	conf->max_charge_current = CONF_MAX_CHARGE_CURRENT;
	conf->sleep_timeout_reset_ms = CONF_SLEEP_TIMEOUT_MS;
	conf->soc_filter_const = CONF_SOC_FILTER_CONST;
	conf->t_bal_lim_start = CONF_T_BAL_LIM_START;
	conf->t_bal_lim_end = CONF_T_BAL_LIM_END;
	conf->t_charge_min = CONF_T_CHARGE_MIN;
	conf->t_charge_mon_en = CONF_T_CHARGE_MON_EN;
}

