// This file is autogenerated by VESC Tool

#ifndef VBMS32_CONFXML_H_
#define VBMS32_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		5940

// Variables
extern uint8_t data_main_config_t_[];

// VBMS32_CONFXML_H_
#endif
