// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// CAN ID
#ifndef CONF_CONTROLLER_ID
#define CONF_CONTROLLER_ID -1
#endif

// CAN Baud Rate
#ifndef CONF_CAN_BAUD_RATE
#define CONF_CAN_BAUD_RATE 2
#endif

// Status Message Rate
#ifndef CONF_CAN_STATUS_RATE_HZ
#define CONF_CAN_STATUS_RATE_HZ 20
#endif

// WiFi Mode
#ifndef CONF_WIFI_MODE
#define CONF_WIFI_MODE 2
#endif

// Station Mode SSID
#ifndef CONF_WIFI_STA_SSID
#define CONF_WIFI_STA_SSID ""
#endif

// Station Mode Key
#ifndef CONF_WIFI_STA_KEY
#define CONF_WIFI_STA_KEY ""
#endif

// Access Point SSID
#ifndef CONF_WIFI_AP_SSID
#define CONF_WIFI_AP_SSID "VESC WiFi"
#endif

// Access Point Key
#ifndef CONF_WIFI_AP_KEY
#define CONF_WIFI_AP_KEY "vesc6wifi"
#endif

// Bluetooth Mode
#ifndef CONF_BLE_MODE
#define CONF_BLE_MODE 1
#endif

// Name
#ifndef CONF_BLE_NAME
#define CONF_BLE_NAME "ExpressT"
#endif

// Bluetooth Pin Code
#ifndef CONF_BLE_PIN
#define CONF_BLE_PIN 123456
#endif

// CONF_DEFAULT_H_
#endif

