// This file is autogenerated by VESC Tool

#ifndef RB_CONFPARSER_H_
#define RB_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		4186312577

// Functions
int32_t rb_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool rb_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void rb_confparser_set_defaults_main_config_t(main_config_t *conf);

// RB_CONFPARSER_H_
#endif
